# https://github.com/nleiva/ee-builds/blob/master/ee-network-image/requirements.yml
collections:
  - name: community.general
  - name: cisco.ios
    version: 6.0.0
  - name: cisco.nxos
  - name: cisco.iosxr
  - name: ansible.netcommon
