- name: Configure ACL
  hosts: routers
  gather_facts: false
  vars_files: acls_vars.yml

  tasks:
    - name: Cleanup builtin
      ansible.builtin.file:
        path: /usr/share/ansible/collections/ansible_collections/cisco
        state: absent

    - name: Debuggery
      ansible.builtin.shell: ansible-galaxy collection list && ansible --version
      delegate_to: localhost
      run_once: true
      ignore_errors: true

    - name: Get ACL Config
      cisco.ios.ios_acls:
        state: "gathered"

    - name: Apply ACL config to device
      cisco.ios.ios_acls:
        state: "{{ acl_state }}"
        config:
          - afi: ipv4
            acls:
              - "{{ acl_50 }}"
