- name: Configure ACL
  hosts: routers
  gather_facts: false
  #vars_files: acls.cfg

  tasks:
    # - name: Use ACL resource module [Cisco IOS]
    #   cisco.ios.ios_acls:
    #     state: replaced
    #     config: "{{ cfg }}"
    #   when: ansible_network_os == 'cisco.ios.ios'

    # - name: Use ACL resource module [Cisco NX-OS]
    #   cisco.nxos.nxos_acls:
    #     state: replaced
    #     config: "{{ cfg }}"
    #   when: ansible_network_os == 'cisco.nxos.nxos'

    # - name: Use ACL resource module [Cisco IOS XR]
    #   cisco.iosxr.iosxr_acls:
    #     state: replaced
    #     config: "{{ cfg }}"
    #   when: ansible_network_os == 'cisco.iosxr.iosxr'
    - name: Cleanup builtin
      ansible.builtin.file:
        path: /usr/share/ansible/collections/ansible_collections/cisco
        state: absent

    - name: Debuggery
      ansible.builtin.shell: ansible-galaxy collection list && ansible --version
      delegate_to: localhost
      run_once: true
      ignore_errors: true
      
    - name: Apply ACL config to device
      cisco.ios.ios_acls:
        state: "{{ acl_state }}"
        config:
          - afi: ipv4
            acls:
              - name: NAT-ACL
                acl_type: extended
                aces:
                - sequence: 10
                  grant: permit
                  protocol: ip
                  source:
                    address: 192.168.1.0
                    wildcard_bits: 0.0.0.255
                  destination:
                    any: true
              - name: Test
                acl_type: extended
                aces:
                - sequence: 10
                  grant: permit
                  protocol: ip
                  source:
                    any: true
                  destination:
                    host: 1.1.1.1
              - name: meraki-fqdn-dns
                acl_type: extended              
              - name: test123
                acl_type: "standard"
                aces:
                  - sequence: 10
                    grant: permit
                    source:
                      address: 8.8.8.8
                    remarks:
                      - "GDNS"
                  - sequence: 20
                    grant: permit
                    source:
                      address: 8.8.4.4
                    remarks:
                      - "GDNS"
              - name: 90
                aces:
                  - sequence: 10
                    remarks:
                      - "Monitoring Tools"
                    grant: permit
                    source:
                      address: 10.56.98.0
                      wildcard_bits: 0.0.0.127
                  - sequence: 20
                    remarks:
                      - "mRNACenter"
                    grant: permit
                    source:
                      address: 10.195.43.10
                      wildcard_bits: 0.0.0.0
                  - sequence: 30
                    remarks:
                      - "mRNACenter"
                    grant: permit
                    source:
                      address: 10.233.39.11
                      wildcard_bits: 0.0.0.0
                  - sequence: 40
                    remarks:
                      - "mRNACenter"
                    grant: permit
                    source:
                      address: 10.233.39.12
                      wildcard_bits: 0.0.0.0
                  - sequence: 50
                    remarks:
                      - "mRNACenter"
                    grant: permit
                    source:
                      address: 10.233.39.13
                      wildcard_bits: 0.0.0.0
                  - sequence: 60
                    remarks:
                      - "Bezos MoonBreeze"
                    grant: permit
                    source:
                      address: 10.84.128.128
                      wildcard_bits: 0.0.0.63