- name: Get cert data
  hosts: routers
  gather_facts: false

  tasks:
    - name: Show device certificates
      cisco.ios.ios_command:
        commands: show crypto pki certificates
      register: __ios_crypto

    - name: Write certs info to local file
      ansible.builtin.copy:
        content: "{{ __ios_crypto.stdout | replace('\\n', '\n') }}"
        dest: /tmp/certs