---
- name: Run command
  hosts: routers
  gather_facts: false

  tasks:
  - name: Write mem
    cisco.ios.ios_command:
      commands:
      - command: 'copy running-config bootflash:copied.cfg'
        prompt: 'Destination filename [copied.cfg]'
        answer: "\r"
      - command: 'write mem'